### ISSUE TITLE
Error during fisrt run

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [arbylee/python-warrior#3]
I can't start the game.
After installing the game with pip, I get this error when I execute pythonwarrior:

```
Traceback (most recent call last):
  File "/usr/local/bin/pythonwarrior", line 20, in <module>
    runner.run()
  File "/usr/local/lib/python2.7/dist-packages/pythonwarrior/runner.py", line 19, in run
    self.game.start()
  File "/usr/local/lib/python2.7/dist-packages/pythonwarrior/game.py", line 21, in start
    self._profile = Profile.load(Config.path_prefix + '/.profile')
  File "/usr/local/lib/python2.7/dist-packages/pythonwarrior/profile.py", line 43, in load
    player = Profile.decode(f.read())
  File "/usr/local/lib/python2.7/dist-packages/pythonwarrior/profile.py", line 38, in decode
    return pickle.loads(base64.b64decode(encoded_profile))
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '\xfe'
```

**Comment by arbylee** [comment]
I'm having trouble reproducing this, can you provide some more details?

Does this happen after you selected difficulty and warrior name?
What difficulty did you choose?
Did you use any special characters in your warrior name?
What OS are you using?

**Comment by schyzophrene-asynchrone** [comment]
> Does this happen after you selected difficulty and warrior name?
> No, it happens just after typing pythonwarrior in konsole.
> What OS are you using?
> Debian Testing. I installed pythonwarrior through pip.

In case there are still some existing files from the last time I used pythonwarrior, could you tell me where are saved the config files ?

**Comment by schyzophrene-asynchrone** [comment]
I think I know where it comes from.
Your app tries to read the file ./.profile to load the profile, and if it does not exits, it creates the directory pythonwarrior and make a config in it.
I have a file .profile in my personnal directory. It's this one:

```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
export GTK_MODULES=globalmenu-gnome
```

Nothing to do with pythonwarrior, obviously...
If I start the game elsewhere, it works perfectly fine.

**Comment by arbylee** [comment]
Good catch, I should change the name of that file to avoid further naming conflicts
